### ISSUE TITLE
Control not returning to SML from called C function

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#102]
I am finding that control sometimes does not return back to SML from a called C function - a seg. fault occurs instead.  When the seg. fault occurs, GDB shows that the C function _does_ return but the backtrace just before the function returns - see [backtrace-exit.txt](https://github.com/polyml/polyml/files/1936876/backtrace-exit.txt) - differs from the backtrace just after entry - see [backtrace-entry.txt](https://github.com/polyml/polyml/files/1936875/backtrace-entry.txt) - which seems surprising.  In particular, stack frame 10 in backtrace-entry.txt is not in backtrace-exit.txt, which is probably due to the saved rip in frame 9 becoming zero.  I suspect that this is the cause of the seg. fault - frame 10 is missing whenever the seg. fault occurs.

The C function is actually g_application_run and during the course of this function control will transfer back to SML via a callback.  Watching the address where the saved rip is stored shows that it is being overwritten during a call to PolyBasicIOGeneral - see [watch_saved_rip.txt](https://github.com/polyml/polyml/files/1936880/watch_saved_rip.txt).  I wondered if the new approach using entry point tables is not re-entrant in some respect?

This issue is not present in Poly/ML 5.6 but occurs in Poly/ML 5.7 and later.  Through bisection, I narrowed this down to the range (ff6aeb930aa4c6a116b0fe16ceedabacb6f9dd6c, 184ba3d4753bfcba6194f5aa8b05426d50b72732] but couldn't test intermediate commits for various reasons.

**Comment by dcjm** [comment]
If the saved Rip at 0x7ffff7e16bb0 is being overwritten by `Set `called from `alloc `this implies that it is in the heap and not, as I would expect, on the C stack. Is this really the return address? I wonder if this is misleading.  It seems unlikely that the original return address would be `ffi_type_sint32`.  Because Poly does not use C linkage conventions backtraces are often wrong.

**Comment by pclayton** [comment]
You're right - these backtraces are nonsense for anything above area1.  What is actually happening is that the call to PolyFFIGeneral (call instruction below) returns and the subsequent ret instruction causes the seg. fault.

    0x425845 <area1+2525>   call   r11
    0x425848 <area1+2528>   mov    rsp,r13
    0x42584b <area1+2531>   mov    r15,QWORD PTR [rbp+0x0
    0x42584f <area1+2535>   cmp    QWORD PTR [rbp+0x20],0x1
    0x425854 <area1+2540>   jne    0x425857 <area1+2543>
    0x425856 <area1+2542>   ret

The value in rsp looks good before the ret instruction executes (it is 0x7ffff7ff4e90, the same as when there is no seg. fault) but it does not appear to be an address in usable memory (although sometimes is an unusable address in usable memory).

1. Without conditions for the seg. fault:

       (gdb) print (void *)(*0x7ffff7ff4e90)
       $1 = (void *) 0x43536a <area1+66818>

2. With conditions for the seg. fault, usually:

       (gdb) print (void *)(*0x7ffff7ff4e90)
       Cannot access memory at address 0x7ffff7ff4e90

   but sometimes:

       (gdb) print (void *)(*0x7ffff7ff4e90)
       $1 = (void *) 0x0

I'll continue to investigate.

**Comment by pclayton** [comment]
I have isolated this issue.  The seg. fault appears to be caused by reading a file above a certain size in an SML function that is run for the first time in a callback from C.  I find that a file size of 1 MB is sufficient to trigger the fault.  (In fact, the threshold seems to vary in the region of 100 kB to 200 kB.)  This occurs with Poly/ML 5.7 and later on my Linux x86_64 system.  (I haven't tested other platforms.)

I have created a small example in [call_c_test_12.tar.gz](https://github.com/polyml/polyml/files/1950252/call_c_test_12.tar.gz).  Use the command `make` to build this.  To create a dummy text file to read, use the command

    ./make_readfile 1000000

and run the example with the command

    ./call_c_test_12

Hopefully this gives a seg. fault.  If no seg. fault occurs, try a larger file size, e.g.

    ./make_readfile 10000000

**Comment by dcjm** [comment]
Thank you for looking at this.  I haven't actually run your test but I'm fairly certain I know what the problem is.  Each thread has two stacks: a fixed-size "C" stack created by the initial thread-creation and an ML stack that can grow as needed.  The ML stack is handled by the Poly/ML run-time system.  I suspect that the callback is causing the ML stack to grow which involves allocating a new stack segment, copying everything over and deallocating the old segment.  The problem arises because the stub code that is calling PolyFFIGeneral is saving the ML stack pointer in r13 before the call and then restoring it afterwards.  r13 is "callee-saved" so gets saved by PolyFFIGeneral but if there has been a callback in the meantime and the stack has moved this will no longer be valid.
This problem only arises with PolyFFIGeneral since that's the only way that there can be a callback to ML.  I need to work out a proper solution but in the meantime you may be able to work around the problem by ensuring the calling thread has recursed deeply and grown the stack before you make the initial call.

**Comment by dcjm** [comment]
I've pushed a commit that seems to have fixed it.  My test programs now work.  Note that this requires the compiler to be be built so run `make compiler` at least once after pulling the fix.  Let me know if this has fixed it for you.

**Comment by pclayton** [comment]
Thanks for the fix.  The attached example above now works with dae2471b.  I can't test the real application with that version due to issue #101 however the real application works using a version created by applying that commit on top of v5.7.1 (44b7b88e).  So I think we can safely assume this issue is fixed!
