### ISSUE TITLE
Compiling from sources: different guides

### ISSUE THREAD

**Issue by GergelyBuday** [polyml/polyml#174]
On the github page it is written at https://github.com/polyml/polyml that:

$ ./configure
$ make
$ make compiler
$ make install

is needed, while on the Poly/ML home page at https://polyml.org/download.html it is written that:

./configure
make
make install

is enough, no make compiler is needed.

Which one is the correct workflow?

**Comment by pclayton** [comment]
You need the `make compiler` step for Poly/ML < 5.9 but it is no longer needed for Poly/ML 5.9.  It looks like `README.md` wasn't updated for Poly/ML 5.9.

This was mentioned on the mailing list [here](http://lists.inf.ed.ac.uk/pipermail/polyml/2021-October/002462.html) (with more details in the message linked from that message).

**Comment by dcjm** [comment]
I've updated `README.md`.
The short answer is that prior to 5.9 `make` on its own built the system using the pre-built compiler for the last release.  When building the git version `make compiler` was used to ensure that any changes to the compiler since the last release were also included.  That's no longer needed since the compiler is now rebuilt during a normal `make`.
