### ISSUE TITLE
Windows polyc missing?

### ISSUE THREAD

**Issue by ryu0** [polyml/polyml#61]
I was digging into the existing binary distributions and I noticed they are missing polyc and the libraries needed to produce standalone binaries. I was hoping the installer would include these libraries somewhere so that you could use an already installed mingw64 compiler to compile standalone binaries from the CMD console or perhaps the MSYS console. I would be willing to write a script to tie it all together like the polyc shell script does for unix environments. Thoughts?

**Comment by dcjm** [comment]
I think the problem is the linker.  It wouldn't be feasible or appropriate to include a linker within the Poly binaries so buliding a stand-alone binary on Windows requires either the MSYS environment or the Visual Studio environment.  There is a Visual Studio "solution" and "project" included in the sources for those who are familiar with that.  For those used to a Unix command line it's possible to build Poly/ML from source within MSYS2 or Cygwin.  Both these build polyc as on Unix.
The Windows binary distribution is really intended for users who expect to be able to download an installer and just run it.

**Comment by ryu0** [comment]
Alright that seems acceptable.
